### ISSUE TITLE
Error receiving pushNotificationUrls: timeout of 1000ms exceeded

### ISSUE THREAD

**Issue by olli0815** [a-i-ks/ioBroker.volumio#32]
**Describe the bug**  
I get an error message and the state is yellow only

	2024-08-18 13:30:20.801	error	Subscription to volumio push notifications failed: timeout of 1000ms exceeded
	2024-08-18 13:30:19.793	error	Error receiving pushNotificationUrls: timeout of 1000ms exceeded

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by a-i-ks** [comment]
It's seems like your Volumio is not responding on the entered network address. Could you please check if you have the correct network address entered and Volumio is also responding.

**Comment by olli0815** [comment]
Oh sorry, you are right.
My fault, thanks.

**Comment by olli0815** [comment]
Sorry

**Comment by olli0815** [comment]
BUT: maybe - if possible - change the error message from E to I in case Volumio is not connected (off).
Because if the Volumio device is off I do not expect any working connection...instead the adapter raises an error message. 
That is not correct, or even unwanted.

**Comment by a-i-ks** [comment]
The problem is: How am I supposed to distinguish between a Volumino host that is intentionally switched off and one that is unintentionally inaccessible? 
I would suggest that you stop the adapter (this can also be done programmatically) when you have switched off Volumino. 
Otherwise I am open to alternative suggestions.

**Comment by olli0815** [comment]
you can check the connection state under "info".
If connection = false -> no error message else error

**Comment by a-i-ks** [comment]
The value under info.connection is set by my adapter code. I set this value to false if ‘checkConnection’ is activated in the options and Volumino does not respond to the ping or, if the push mechanism is activated, to the subscription check. This means that this value is not set by Volumino, but by me after a failed connection attempt. 
So I still don't see any way to distinguish between
 ‘I can't reach Volumino because I intentionally shut down the host, so I expect at most a warning in the logs’ 
  and
  ‘I can't reach Volumino due to an unexpected network problem or because Volumino crashed and I expect an error message in the log’.  
I could perhaps build in a feature where the adapter switches to a failure state after a certain number of connection retries and stops logging. But you could also just disable the connection check ;)

**Comment by olli0815** [comment]
to be honest the only reason I notice was that the connection was false (No ping to volumio host) and error message in my log. 
No further control mechanism in my setup just the message that is misleading when host is not reachable - subscription stae is lost by default, no error.

If you just change the message type from E to I I'm happy because it will not written in the log every minute or so ;-)

**Comment by olli0815** [comment]
...so its more a wish then a bug ;-)
And by the way: thanks for the adapter !

**Comment by a-i-ks** [comment]
I will try to improve the logging with the next version. However, I cannot yet give an exact date for the next release. At the moment I have little time for my hobby projects.
