### ISSUE TITLE
Support of multiple adapter instances 

### ISSUE THREAD

**Issue by Frank-2021** [a-i-ks/ioBroker.volumio#7]
I am runing two instances in my house so I he first volumio instance (volumio.0) - everything is perfect :-)

But the second instance (volumio.1) wont run. 
If I disable the volumio.0 the volumio.1 becomes green (runs). But then volumio.0 wont run.

So it seems like only one volumio instance can work.

![08-03-_2021_09-30-13](https://user-images.githubusercontent.com/80247973/110295409-5c75c500-7ff1-11eb-97f3-87ec4e08c06b.png)
![08-03-_2021_09-30-33](https://user-images.githubusercontent.com/80247973/110295411-5d0e5b80-7ff1-11eb-8dae-6185cf259cd1.png)
![08-03-_2021_09-30-57](https://user-images.githubusercontent.com/80247973/110295414-5da6f200-7ff1-11eb-8faf-8fc04092ff68.png)
![08-03-_2021_09-32-23](https://user-images.githubusercontent.com/80247973/110295416-5e3f8880-7ff1-11eb-9846-b7afe567dbde.png)

**Comment by a-i-ks** [comment]
In fact, the adapter is currently only capable to support a single instance.
I would put the support of multiple instances on the feature list for a future version, but unfortunately I can't give a schedule for the next release, because I have only sporadic time in my spare time for development. 
Any help for further development is welcome.

**Comment by mcm1957** [comment]
Please either support multiple instances OR set singleton attribute at io-package.json

**Comment by a-i-ks** [comment]
Better late than never. The upcoming version 0.2.0 will support multiple adapter instances. I will release it within this week.
